name: Deploy React to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies & Build
      run: |
        cd fe
        npm install
        npm run build

    - name: Deploy build to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "fe/build/*"
        target: "/var/www/cosmeticcenter/fe/build"
